---
title: "R Notebook 2025: Converis PM GRANTS import"
output: 
  html_document:
    toc: true
    toc_depth: 5
    toc_float: TRUE

---


# Introduction
De output van verschillende API's geschikt maken voor het importeren in Converis PM GRANTS entiteit.

# Setup


## Load packages

```{r, PACKAGES, echo = TRUE, eval = TRUE}

# Packages needed
  package.list <- c("conflicted", "reprex", "tidyverse", "rmarkdown", 
                    "data.table", "vctrs", "openxlsx")


# Install missing packages 
  new.packages <- package.list[!(package.list %in% installed.packages()[,"Package"])]
  if(length(new.packages)) install.packages(new.packages)

  
# Load packages needed (and subdue)
  invisible(lapply(package.list, library, character.only = TRUE))


```



# Data

```{r}

# Read files

# Read: NWO grants
  LEI_NWO_grants <- read.xlsx("DATA_GRANTS/NWO_PROJECTS/NWO_LEI_projecten.xlsx", sheet = "Sheet 1")
  LEI_NWO_grants_output <- read.xlsx("DATA_GRANTS/NWO_PROJECTS/NWO_LEI_onderzoeksoutput.xlsx", sheet = "Sheet 1")


# Schoonmaken bestanden 
  LEI_NWO_grants <- clean_names(LEI_NWO_grants)
  LEI_NWO_grants_output <- clean_names(LEI_NWO_grants_output)



# Check headers
#  NWO_grants <- colnames(LEI_NWO_grants)
#  print(NWO_grants)
#  NWO_output <- colnames(LEI_NWO_grants_output)
#  print(NWO_output)



# Create RESULTAAT_INLEESBESTAND directory if not there
  ifelse(!dir.exists("RESULTAAT_INLEESBESTAND"), dir.create("RESULTAAT_INLEESBESTAND"), "Folder exists already")

```

